title: Vladimir Zaytsev Blog
tagline:
description: > # This means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://zaycev.github.io" # The base hostname & protocol for your site
# image: /images/site-image.jpg # The site cover image on the home page
feed: /feed.xml # Set it if your feed path is not /feed.xml, e.g. /atom.xml
paginate: 10 # http://jekyllrb.com/docs/pagination/

destination: /Users/zaitsev/code/zblog/zaycev.github.com
disqus_shortname: znlp
google_analytics_tracking_id: UA-47310787-1


# Site navigation
nav:
  - title: "Posts"
    url:   "/"
  - title: "About Me"
    url:   "/about/"

social_links:
  - title: "Twitter"
    url:   "https://twitter.com/vladimirzaytsev"
  - title: "Facebook"
    url:   "https://www.facebook.com/vladimir.zaytsev"
  - title: "Github"
    url:   "https://github.com/zaycev"
  - title: "Instagram"
    url:   "http://instagram.com/metanerd"
  - title: "LinkedIn"
    url:   "https://www.linkedin.com/in/vladimir-zaytsev-10632a2b"
  - title: "Email"
    url:   "mailto:zaytsev@usc.edu"

authors:
  zaytsev:
    name: Vova Zaytsev
    website: https://zaycev.github.io/about
    bio: ML and NLP engineer at A9
    avatar: /images/vova-zaytsev-avatar.jpg

# Extra Open Graph and Twitter Cards settings for social sharing
og_image: # Fallback og:image when no page.image or site.image. at least 200 x 200px.
twitter_site: # twitter:site. Your Twitter username without "@"

# "Archive pages for your Jekyll tags and categories."
# https://github.com/jekyll/jekyll-archives
gems:
  - jekyll-paginate
#   - jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
